# Generated by Django 5.2.7 on 2025-11-15 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem_unit_cost'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='salesinquiry',
            options={'ordering': ['-inquiry_date'], 'verbose_name_plural': 'Sales inquiries'},
        ),
        migrations.AlterModelOptions(
            name='salesinquiryitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.PositiveIntegerField(default=30, help_text='Payment terms in days'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='total_estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinquiry',
            name='inquiry_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['expected_ship_date'], name='sales_saleo_expecte_e9b207_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinquiry',
            index=models.Index(fields=['priority'], name='sales_sales_priorit_ee9a68_idx'),
        ),
    ]
