# Generated by Django 5.2.7 on 2025-11-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesinquiryitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_code_4ece8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_custome_890109_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_is_acti_1b1d19_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_invoi_invoice_51f3c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_invoi_status_4e3758_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_invoi_due_dat_a262a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleorder',
            name='sales_saleo_order_n_138a41_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleorder',
            name='sales_saleo_status_4180aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleorder',
            name='sales_saleo_custome_739fe5_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleorder',
            name='sales_saleo_order_d_711f25_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleorder',
            name='sales_saleo_expecte_e9b207_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinquiry',
            name='sales_sales_inquiry_ef848e_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinquiry',
            name='sales_sales_status_5bf244_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinquiry',
            name='sales_sales_custome_74c3db_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinquiry',
            name='sales_sales_require_ae29bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinquiry',
            name='sales_sales_priorit_ee9a68_idx',
        ),
    ]
