# Generated by Django 5.2.7 on 2025-11-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockitem_barcode_stockitem_is_serialized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodesession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='barcodesession',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='is_serialized',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='rack_number',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='shelf_location',
        ),
        migrations.DeleteModel(
            name='BarcodeScan',
        ),
        migrations.DeleteModel(
            name='BarcodeSession',
        ),
    ]
