# Generated by Django 5.2.7 on 2025-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_barcodesession_created_by_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockitem',
            name='inventory_s_quantit_82d8d9_idx',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='reorder_threshold',
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['quantity'], name='inventory_s_quantit_93001f_idx'),
        ),
    ]
