# Generated by Django 5.2.7 on 2025-11-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stockitem_inventory_s_quantit_82d8d9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='unit_cost',
        ),
    ]
