# Generated by Django 5.2.7 on 2025-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_stockitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit in this stock item (for batch-specific costing).', max_digits=10),
        ),
    ]
