# Generated by Django 5.2.7 on 2025-11-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='new_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity after adjustment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='previous_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity before adjustment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('count', 'Stock Count'), ('quality', 'Quality Check')], max_length=20),
        ),
    ]
