# Generated by Django 5.2.7 on 2025-11-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('production', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_asset', to='production.workorder'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='maintenance_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maintenance.maintenanceorder'),
        ),
        migrations.AddField(
            model_name='sparepartusage',
            name='maintenance_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='maintenance.maintenanceorder'),
        ),
        migrations.AddField(
            model_name='sparepartusage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='sparepartusage',
            name='stock_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockitem'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='maintenance_asset_c_23b943_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='maintenance_asset_t_d337af_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='maintenance_status_2b9a97_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_maintenance'], name='maintenance_next_ma_c48241_idx'),
        ),
    ]
