# Generated by Django 5.2.7 on 2025-11-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='QCChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quality.qcchecklist')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('rework', 'Sent for Rework')], default='pending', max_length=20)),
                ('quantity_tested', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity_passed', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quantity_failed', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qcchecklist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QCCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='qc_certificates/')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('qc_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quality.qcrecord')),
            ],
        ),
        migrations.CreateModel(
            name='QCAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qc_attachments/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('qc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality.qcrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('is_pass', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qcchecklistitem')),
                ('qc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='quality.qcrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['record_number'], name='quality_qcr_record__189469_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['status'], name='quality_qcr_status_6ee509_idx'),
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['batch_number'], name='quality_qcr_batch_n_176816_idx'),
        ),
    ]
