# Generated by Django 5.2.7 on 2025-10-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_sku', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=200)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumption', to='production.workorder')),
            ],
            options={
                'ordering': ['material_sku'],
            },
        ),
    ]
